// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AIcon: typeof import('./components/a-icon/index.vue')['default']
    ATransition: typeof import('./components/a-transition/index.vue')['default']
    APopup: typeof import('./components/a-popup/index.vue')['default']
  }
}

export {}
