// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('./components/a-button/index.vue')['default']
    AIcon: typeof import('./components/a-icon/index.vue')['default']
    APopup: typeof import('./components/a-popup/index.vue')['default']
    ATransition: typeof import('./components/a-transition/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
